### ISSUE TITLE
When clicking cancel button, extra buttons not hiding

### ISSUE THREAD

**Issue by maeishoj** [andrew-mestas/swalExtend#1]
Hi there.

Thanks for this! Very useful indeed.

I was wondering why when you press cancel the extra buttons are not hidden ?

**Comment by andrew-mestas** [comment]
Hey thank you for the nice remarks. Things have been a little busy lately, but I'll look into this and get back to you as soon as possible.

**Comment by andrew-mestas** [comment]
Can you attach an example of what you are trying to do because I'm not sure what you mean. The extra buttons are children of the parent sweet alert box which hides after user input. I do notice when user confirms if the box does not close the extra buttons will still exist. Attaching a CodePen to try and replicate.

[CodePen SwalExtend](https://codepen.io/andrew-mestas/pen/BWNXRN)

**Comment by andrew-mestas** [comment]
Addressed in latest commit 4c97432d706a982f7485458cbb82d945c47ffd32
